[package]
name = "vpncloud"
version = "0.9.0"
authors = ["Dennis Schwerdel <schwerdel@googlemail.com>"]
build = "build.rs"
license = "GPL-3.0"
description = "Peer-to-peer VPN"
homepage = "https://github.com/dswd/vpncloud"
repository = "https://github.com/dswd/vpncloud"
keywords = ["vpn", "p2p", "tun", "tap", "network"]
readme = "README.md"

[dependencies]
time = "0.1"
docopt = "^1"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
log = { version = "0.4", features = ["std"] }
signal = "0.6"
libc = "0.2"
rand = "0.6"
fnv = "1"
net2 = "0.2"
bitflags = "^1"
yaml-rust = "0.4"
igd = "0.7"
siphasher = "0.3"
daemonize = "0.3"
ring = "0.13"

[build-dependencies]
cc = "^1"
pkg-config = "0.3"

[features]
default = []
bench = []
system-libsodium = []

[profile.release]
lto = true

[profile.dev]
lto = false

[profile.test]
lto = false
